### ISSUE TITLE
Better proposed header to encourage testing

### ISSUE THREAD

**Issue by cpaelzer** [canonical-server/dev-summary#10]
Once we fixed up #7 and #8  we then should also add a header to call for verification of proposed.
Like:

Please consider testing those by enabling proposed [1] and testing packages for update regressions as well as to verify [2] the targeted bug to be fixed.
[1]: https://wiki.ubuntu.com/Testing/EnableProposed
[2]: https://wiki.ubuntu.com/StableReleaseUpdates#Verification

**Comment by cpaelzer** [comment]
Again how we want to define links is up for debate and might be changed along our discussion.
But lets propose something to discuss on first.
Ignore the extra '

New looks like
```
 ### Proposed Uploads to the Supported Releases
     Please consider testing those by enabling proposed [1]
     and testing packages for update-regressions as well as
     to verify [2] the targeted bug to be fixed.
     [1]: https://wiki.ubuntu.com/Testing/EnableProposed
     [2]: https://wiki.ubuntu.com/StableReleaseUpdates#Verification

 ntp, artful, https://launchpad.net/ubuntu/+source/ntp/1:4.2.8p10+dfsg-5ubuntu3.1, paelzer
 slof, xenial, https://launchpad.net/ubuntu/+source/slof/20151103+dfsg-1ubuntu1.1, paelzer
 slof, zesty, https://launchpad.net/ubuntu/+source/slof/20161019+dfsg-1ubuntu0.1, paelzer
 strongswan, xenial, https://launchpad.net/ubuntu/+source/strongswan/5.3.5-1ubuntu3.5, paelzer
 Total: 4
```

**Comment by cpaelzer** [comment]
PR #11 has a suggested fix for the format to be discussed

**Comment by cpaelzer** [comment]
Discussed to focus on markdown, so pushing a version with that in mind.

**Comment by powersj** [comment]
Closing due to pull request from @cpaelzer  thank you!
