### ISSUE TITLE
Issues in package detection

### ISSUE THREAD

**Issue by cpaelzer** [canonical-server/dev-summary#7]
Hi,
the current output suggests all changes got released, but that is not true.

In the mail of this week we had:
```
### Uploads to the Development Release
iproute2, artful, 4.9.0-1ubuntu2.1, paelzer
iproute2, zesty, 4.9.0-1ubuntu1.1, paelzer
iproute2, xenial, 4.3.0-1ubuntu3.16.04.3, paelzer
iproute2, trusty, 3.12.0-2ubuntu1.2, paelzer
iproute2, trusty, 3.12.0-2ubuntu1.1, nacc
```

That has multiple issues:

1. it is listed as "Uploads to the Development Release" but actually this has one to bionic and a bunch which are SRUs
2. looking at [the upload](https://launchpad.net/ubuntu/+source/iproute2/4.9.0-1ubuntu2.1) "paelzer" is only the sponsor, we should list the author instead which is listed as "Uploaded by:" on LP
3. furthermore currently this is only in -proposed, so we should split uploads to released Ubuntu into "-proposed, please test + link to enable proposed" and "-updates, now available generally"

I'm not sure if this will be fixed in one go, but I file it as one.
If it turns out to be easy to fix parts of it we can break it into several issues later on.

**Comment by powersj** [comment]
1 is fixed, the print code had the dev function printing the with SRU header and the SRU function printing the dev header.

**Comment by powersj** [comment]
2 is now solved by using package_creator_link instead of the package_signer_link see: https://launchpad.net/+apidoc/devel.html#source_package_publishing_history

This field can be None and will fall back to the signer if it is.

**Comment by powersj** [comment]
@cpaelzer can you file another bug for your 3rd point, namely reporting SRU uploads into two categories: 1) proposed + please test and 2) uploads now available?

I am going to close this as I believe the original errors are now fixed. Thanks for catching these!

**Comment by powersj** [comment]
Here is an example of what I have so far:
https://paste.ubuntu.com/26309067/

**Comment by cpaelzer** [comment]
Opened issue #8 and issue #9 for the follow on improvements.
