### ISSUE TITLE
Drop already released uploads from proposed

### ISSUE THREAD

**Issue by cpaelzer** [canonical-server/dev-summary#8]
Ownership looks good now since issue #7 is mostly fixed, although I wonder on the completeness of #1 due to
"corosync, trusty, 2.3.3-1ubuntu4, vtapia"
being in both categories.

I think I see what happens as I know the details of the slof case.
There we see:
Proposed:
```
slof, xenial, 20151103+dfsg-1ubuntu1.1, paelzer
slof, zesty, 20161019+dfsg-1ubuntu0.1, paelzer
slof, artful, 20170724+dfsg-1ubuntu0.1, paelzer
```

SRU
`slof, artful, 20170724+dfsg-1ubuntu0.1, paelzer
`
In fact all three moved into proposed recently, but the artful upload was already released.
So we should construct the lists as you currently do, but before reporting do:

`Proposed_list = Proposed_list - SRU List.`

Once we fixed this up we then should also add a header to call for verification of proposed.
Like:
```
Please consider testing those by enabling proposed [1] and testing packages for update regressions as well as to verify [2] the targeted bug to be fixed.
[1]: https://wiki.ubuntu.com/Testing/EnableProposed
[2]: https://wiki.ubuntu.com/StableReleaseUpdates#Verification
```

**Comment by cpaelzer** [comment]
Split the proper filtering from the header to encourage testing -> header is issue #10

**Comment by cpaelzer** [comment]
PR #11 has a fix for the list handling

**Comment by powersj** [comment]
Closing due to pull request from @cpaelzer  thank you!
