### ISSUE TITLE
List bugs addressed by uploads

### ISSUE THREAD

**Issue by cpaelzer** [canonical-server/dev-summary#9]
In the lists that we have for Proposed and SRU uploads it would be great to have them augmented with bugs (and links to them). A list of bugs can easily kill the format and make things noisy.
But there would be an easy way to "lead" people to where they get the data - the upload itself, which will link to bugs from there via LP processing the changelog.

So the following
corosync, trusty, 2.3.3-1ubuntu4, vtapia
corosync, xenial, 2.3.5-3ubuntu2, vtapia

Could be:
corosync, trusty, [2.3.3-1ubuntu4](https://launchpad.net/ubuntu/+source/corosync/2.3.3-1ubuntu4), vtapia
corosync, xenial, [2.3.5-3ubuntu2](https://launchpad.net/ubuntu/+source/corosync/2.3.5-3ubuntu2), vtapia

We already have all the data, it essentially will always be:
`https://launchpad.net/ubuntu/+source/<package>/<version>`

**Comment by cpaelzer** [comment]
These days we have no links at all in this section yet.
The other parts of the summary uses a very verbose format of
  `[text](url)`
While this is certainly the biggest compat, it seems the least readable :-/.
Do we have to follow that format for max mail client compatibility?

**Comment by cpaelzer** [comment]
```
corosync, trusty, [2.3.3-1ubuntu4](https://launchpad.net/ubuntu/+source/corosync/2.3.3-1ubuntu4), vtapia
corosync, xenial, [2.3.5-3ubuntu2](https://launchpad.net/ubuntu/+source/corosync/2.3.5-3ubuntu2), vtapia
juju-core, xenial, [2.3.1-0ubuntu0.16.04.1](https://launchpad.net/ubuntu/+source/juju-core/2.3.1-0ubuntu0.16.04.1), nskaggs
juju-core, zesty, [2.3.1-0ubuntu0.17.04.1](https://launchpad.net/ubuntu/+source/juju-core/2.3.1-0ubuntu0.17.04.1), nskaggs
libseccomp, xenial, [2.3.1-2.1ubuntu2~16.04.1](https://launchpad.net/ubuntu/+source/libseccomp/2.3.1-2.1ubuntu2~16.04.1), xnox
slof, artful, [20170724+dfsg-1ubuntu0.1](https://launchpad.net/ubuntu/+source/slof/20170724+dfsg-1ubuntu0.1), paelzer
strongswan, zesty, [5.5.1-1ubuntu3.3](https://launchpad.net/ubuntu/+source/strongswan/5.5.1-1ubuntu3.3), paelzer
strongswan, artful, [5.5.1-4ubuntu2.2](https://launchpad.net/ubuntu/+source/strongswan/5.5.1-4ubuntu2.2), paelzer
sysstat, artful, [11.5.7-1ubuntu2](https://launchpad.net/ubuntu/+source/sysstat/11.5.7-1ubuntu2), dgadomski
sysstat, xenial, [11.2.0-1ubuntu0.2](https://launchpad.net/ubuntu/+source/sysstat/11.2.0-1ubuntu0.2), dgadomski
sysstat, zesty, [11.4.3-1ubuntu1](https://launchpad.net/ubuntu/+source/sysstat/11.4.3-1ubuntu1), dgadomski

```

I think this format is ugly, just the link would be nicer to read so that is what I'm going to propose at first until we discussed.

**Comment by cpaelzer** [comment]
```
libseccomp, xenial, https://launchpad.net/ubuntu/+source/libseccomp/2.3.1-2.1ubuntu2~16.04.1, xnox
slof, artful, https://launchpad.net/ubuntu/+source/slof/20170724+dfsg-1ubuntu0.1, paelzer
strongswan, zesty, https://launchpad.net/ubuntu/+source/strongswan/5.5.1-1ubuntu3.3, paelzer
strongswan, artful, https://launchpad.net/ubuntu/+source/strongswan/5.5.1-4ubuntu2.2, paelzer
sysstat, artful, https://launchpad.net/ubuntu/+source/sysstat/11.5.7-1ubuntu2, dgadomski
```

Better than the markdown format, as if ready without MD it was too noisy (see former comment)
Best would be to fully hide links, but that needs the discussion of us expecting readers have html mail readers or not.
So this is up for discussion.

**Comment by cpaelzer** [comment]
PR #11 has a suggested fix for the format to be discussed

**Comment by cpaelzer** [comment]
Discussed to focus on markdown, so pushing a version with that in mind.

**Comment by powersj** [comment]
Closing due to pull request from @cpaelzer  thank you!
